### PR TITLE
Redesign Cleanup

### LINKED ISSUE #203: Navbar flex centering
The navbar isn't properly centered due to how flex works in CSS

If 3 items are centered in a flexbox but the left and right are different sizes, the center object is offset by the difference.

Should be an easy fix but not my current priority so I'm putting this issue

### PR DESCRIPTION
**Pull request by nilsstreedain**
# Redesign Cleanup

## Screenshots
SCR-20240526-dobz
SCR-20240526-dohl
SCR-20240526-doek
image

## Description
This PR primarily consists of cleanup and refinement of changes made by @Durbin-Elijah. Some additional changes have also been added, see below:
- Completed redesign and consolidated styling for Home and Courses pages
- Redesigned PageButton pop-up.
- Added favicon
- Refactored most of index.css into individual component style sheets
- Fixed broken logo bug
- Redesign navbar (top navbar and teacher sidebar)
- Fix student crash bug upon empty section (still need to address missing lectures)
- Fix broken student course links
- Update roster list view
- Update react bootstrap button styling to current color scheme (can't seem to change the default color of :active or :focus?)

Fixes #203 

## Checklist:
Before you submit your Pull Request, please make sure you have completed the following tasks:
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have tagged my PR with the appropriate label(s).

### CODE REVIEW

**Review by Durbin-Elijah — COMMENTED** [review]
Super clean! Everything looks super clean and navigates very well.
I only found 1 super tiny issue with the create course button overlapping when scrolling.

image

I think it should be a super simple fix and then it should be all good to merge.

**Comment by Durbin-Elijah** [comment]
image
I actually noticed 1 other thing I think the container for these elements need some margin at the bottom

**Comment by nilsstreedain** [comment]
> Super clean! Everything looks super clean and navigates very well. I only found 1 super tiny issue with the create course button overlapping when scrolling.
> 
> I think it should be a super simple fix and then it should be all good to merge.

Ahh, for some reason it renders differently on chrome than safari, fixed it with z-index.

**Comment by Durbin-Elijah** [comment]
> > Super clean! Everything looks super clean and navigates very well. I only found 1 super tiny issue with the create course button overlapping when scrolling.
> > I think it should be a super simple fix and then it should be all good to merge.
> 
> Ahh, for some reason it renders differently on chrome than safari, fixed it with z-index.

Ahh it works a lot better now in that way, except I am now unable to click the button haha. Definitely seems like some weird interaction differences between the browsers with z-index, as I can see the landing header is covering it up when inspecting.

image

**Comment by nilsstreedain** [comment]
> EDIT: It's not the header blocking it, since it's part of the header, its the courses div.

Oh man XD! Try now

**Review by Durbin-Elijah — APPROVED** [review]
Perfect, works great and look amazing, the website will be so visually appealing for the demo and expo with all these changes.

**Pull request merged**
