### PR TITLE
Merge rumseyn/update-dependencies

### PR DESCRIPTION
**Pull request by n8srumsey**
# Pull Request Template

## Screenshots

N/A

## Description
These changes migrates the project from the now deprecated `create-react-app` to `vite` as well as resolves node package security vulnerabilities from old dependency versions. With this change, I recommend you all run `npm install` in the root directory to install the new npm dependencies. Additionally, I recommend you to run `docker compose build` in the `server/` directory to update the cached container build.

Additionally, for the `client/` code, the package `vitest` was added and configured to run integration and unit tests, with a placeholder test already written. This PR does not aim to implement front end testing; it was only setting up the dependencies for it to be run in the first place.

Fixes # N/A - No issue

## Additional Information
The necessary changes to documentation have not been made. This is largely due to the priority of providing a stable solution for the project dependencies for group members to initiate work.

## Checklist:
Before you submit your Pull Request, please make sure you have completed the following tasks:
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have tagged my PR with the appropriate label(s).

### CODE REVIEW

**Comment by Sage-m** [comment]
Looks good to me

**Comment by Sage-m** [comment]
LGTM

**Review by n8srumsey — COMMENTED** [review]
Previously received verbal approval, waited for over 2 weeks for official code review, so pushing this through now

**Review by SonnySideUp37 — APPROVED** [review]
Looks good.

**Review by enjiwood — APPROVED** [review]

**Review by sgoober — APPROVED** [review]

**Pull request merged**
