### PR TITLE
Containerize backend app and MySQL database.

### PR DESCRIPTION
**Pull request by Justin-Fernbaugh**
# Pull Request Template

## Description
Firstly, I created a container for the NodeJS backend in the Dockerfile. Secondly, utilized docker-compose to deploy the backend container and MySQL container. Important to note, that the dev and test databases are created using `db/init.sql`. Seeding and migration are done only on the first run using `entrypoint.sh` which creates `CONTAINER_FIRST_STARTUP` inside the container to track whether initialization needs to occur.

Fixes # (issue)

## Checklist:
Before you submit your Pull Request, please make sure you have completed the following tasks:
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] New and existing unit tests pass locally with my changes.
- [X] Any dependent changes have been merged and published in downstream modules.
- [X] I have tagged my PR with the appropriate label(s).

### CODE REVIEW

**Comment by nilsstreedain** [comment]
I followed the commands added in the server/README.md but I'm having some issues getting it running. I'm getting the following output from myclassroom_backend, could I be doing something wrong here?
```
2024-05-23 14:18:22 Container first start intializing database...
2024-05-23 14:18:22 
2024-05-23 14:18:22 Sequelize CLI [Node: 22.2.0, CLI: 6.5.2, ORM: 6.37.3]
2024-05-23 14:18:22 
2024-05-23 14:18:22 Loaded configuration file "config/db.config.js".
2024-05-23 14:18:22 Using environment "test".
2024-05-23 14:18:22 
2024-05-23 14:18:22 
2024-05-23 14:18:22 Completed migrating and seeding databases.
2024-05-23 14:18:22 
2024-05-23 14:18:22 > myclassroom@1.0.0 start:dev
2024-05-23 14:18:22 > nodemon app/server.js --NODE_ENV=development
2024-05-23 14:18:22 
2024-05-23 14:18:22 [nodemon] 3.1.0
2024-05-23 14:18:22 [nodemon] to restart at any time, enter `rs`
2024-05-23 14:18:22 [nodemon] watching path(s): *.*
2024-05-23 14:18:22 [nodemon] watching extensions: js,mjs,cjs,json
2024-05-23 14:18:22 [nodemon] starting `node app/server.js --NODE_ENV=development`
2024-05-23 14:18:22 [2024-05-23 09:18:22.824 PM] ERROR:         Unable to connect to sequelize database
2024-05-23 14:18:22 [2024-05-23 09:18:22.825 PM] ERROR:         Plugin 'mysql_native_password' is not loaded
2024-05-23 14:18:22 SequelizeConnectionError: Plugin 'mysql_native_password' is not loaded
2024-05-23 14:18:22     at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)
2024-05-23 14:18:22     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-23 14:18:22     at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
2024-05-23 14:18:22     at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
2024-05-23 14:18:22     at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
2024-05-23 14:18:22     at async /app/node_modules/sequelize/lib/sequelize.js:305:26
2024-05-23 14:18:22     at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)
2024-05-23 14:18:22 [nodemon] clean exit - waiting for changes before restart
2024-05-23 14:18:22 ERROR: Access denied for user 'testadmin'@'172.19.0.3' (using password: YES)
```

**Comment by Justin-Fernbaugh** [comment]
> I followed the commands added in the server/README.md but I'm having some issues getting it running. I'm getting the following output from myclassroom_backend, could I be doing something wrong here?
> 
> ```
> 2024-05-23 14:26:11 Container first start intializing database...
> 2024-05-23 14:26:12 
> 2024-05-23 14:26:12 Sequelize CLI [Node: 22.2.0, CLI: 6.5.2, ORM: 6.37.3]
> 2024-05-23 14:26:12 
> 2024-05-23 14:26:12 Loaded configuration file "config/db.config.js".
> 2024-05-23 14:26:12 Using environment "test".
> 2024-05-23 14:26:12 
> 2024-05-23 14:26:12 
> 2024-05-23 14:26:12 Completed migrating and seeding databases.
> 2024-05-23 14:26:12 
> 2024-05-23 14:26:12 > myclassroom@1.0.0 start:dev
> 2024-05-23 14:26:12 > nodemon app/server.js --NODE_ENV=development
> 2024-05-23 14:26:12 
> 2024-05-23 14:26:12 [nodemon] 3.1.0
> 2024-05-23 14:26:12 [nodemon] to restart at any time, enter `rs`
> 2024-05-23 14:26:12 [nodemon] watching path(s): *.*
> 2024-05-23 14:26:12 [nodemon] watching extensions: js,mjs,cjs,json
> 2024-05-23 14:26:12 [nodemon] starting `node app/server.js --NODE_ENV=development`
> 2024-05-23 14:26:12 [2024-05-23 09:26:12.581 PM] ERROR:         Unable to connect to sequelize database
> 2024-05-23 14:26:12 [2024-05-23 09:26:12.582 PM] ERROR:         Plugin 'mysql_native_password' is not loaded
> 2024-05-23 14:26:12 SequelizeConnectionError: Plugin 'mysql_native_password' is not loaded
> 2024-05-23 14:26:12     at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)
> 2024-05-23 14:26:12     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-05-23 14:26:12     at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
> 2024-05-23 14:26:12     at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
> 2024-05-23 14:26:12     at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
> 2024-05-23 14:26:12     at async /app/node_modules/sequelize/lib/sequelize.js:305:26
> 2024-05-23 14:26:12     at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)
> 2024-05-23 14:26:12 [nodemon] clean exit - waiting for changes before restart
> 2024-05-23 14:26:12 ERROR: Plugin 'mysql_native_password' is not loaded
> ```

I don't think it's related to anything you did; Might just be a machine difference. Just pushed an update to use legacy authentication and we'll see if that fixes it

**Comment by Justin-Fernbaugh** [comment]
> > I followed the commands added in the server/README.md but I'm having some issues getting it running. I'm getting the following output from myclassroom_backend, could I be doing something wrong here?
> > ```
> > 2024-05-23 14:26:11 Container first start intializing database...
> > 2024-05-23 14:26:12 
> > 2024-05-23 14:26:12 Sequelize CLI [Node: 22.2.0, CLI: 6.5.2, ORM: 6.37.3]
> > 2024-05-23 14:26:12 
> > 2024-05-23 14:26:12 Loaded configuration file "config/db.config.js".
> > 2024-05-23 14:26:12 Using environment "test".
> > 2024-05-23 14:26:12 
> > 2024-05-23 14:26:12 
> > 2024-05-23 14:26:12 Completed migrating and seeding databases.
> > 2024-05-23 14:26:12 
> > 2024-05-23 14:26:12 > myclassroom@1.0.0 start:dev
> > 2024-05-23 14:26:12 > nodemon app/server.js --NODE_ENV=development
> > 2024-05-23 14:26:12 
> > 2024-05-23 14:26:12 [nodemon] 3.1.0
> > 2024-05-23 14:26:12 [nodemon] to restart at any time, enter `rs`
> > 2024-05-23 14:26:12 [nodemon] watching path(s): *.*
> > 2024-05-23 14:26:12 [nodemon] watching extensions: js,mjs,cjs,json
> > 2024-05-23 14:26:12 [nodemon] starting `node app/server.js --NODE_ENV=development`
> > 2024-05-23 14:26:12 [2024-05-23 09:26:12.581 PM] ERROR:         Unable to connect to sequelize database
> > 2024-05-23 14:26:12 [2024-05-23 09:26:12.582 PM] ERROR:         Plugin 'mysql_native_password' is not loaded
> > 2024-05-23 14:26:12 SequelizeConnectionError: Plugin 'mysql_native_password' is not loaded
> > 2024-05-23 14:26:12     at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)
> > 2024-05-23 14:26:12     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > 2024-05-23 14:26:12     at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
> > 2024-05-23 14:26:12     at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
> > 2024-05-23 14:26:12     at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
> > 2024-05-23 14:26:12     at async /app/node_modules/sequelize/lib/sequelize.js:305:26
> > 2024-05-23 14:26:12     at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)
> > 2024-05-23 14:26:12 [nodemon] clean exit - waiting for changes before restart
> > 2024-05-23 14:26:12 ERROR: Plugin 'mysql_native_password' is not loaded
> > ```
> 
> I don't think it's related to anything you did; Might just be a machine difference. Just pushed an update to use legacy authentication and we'll see if that fixes it

Yeah, I should be able to do this, would you be able to point me to which commit this starts so I can remove the changes?

**Review by nilsstreedain — APPROVED** [review]
Looks great to me, tested and fully working!

**Pull request merged**
